### ISSUE TITLE
ezCol.py crash while searching for un unknown ezConStudy./data/ directory

### ISSUE THREAD

**Issue by StudioDanton** [tedcline/ezRA#5]
Hi Ted,

Had a strange error pop up trying to use for the first time ezCon.py to process a 2 hours acquisition test.
Had to create manualy a 'ezConStudydata' directory at the same level of my 'data' directory to overcome the error.
Seems to be a misunderstanding between my pathname and the way it is used by the script.

### Setup

**Processing :**
OS: Windows 10 x64 22H2 Build 19045.4412
Python v3.8.10
using programRevision = `ezCon240108a.py`

### Commands

_Failed when using command:_
`python ../ezRA/ezCon.py ./data/ObsStJean240524_19.txt`

### Output on Failure

```
   openFileStudy ===============
   opening ezConStudy./data/ObsStJean240524_19.txt
Traceback (most recent call last):
  File "../ezRA/ezCon.py", line 10345, in <module>
    main()
  File "../ezRA/ezCon.py", line 9982, in main
    openFileStudy()         # In case it will eventually error.  Creates fileWriteNameStudy, fileWriteStudy
  File "../ezRA/ezCon.py", line 1857, in openFileStudy
    fileWriteStudy = open(fileWriteNameStudy, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'ezConStudy./data/ObsStJean240524_19.txt'
```

**Comment by StudioDanton** [comment]
As a workaround, in subroutine `openFileStudy()`, I've modify `ezConStudy` from a prefix to a sufix :
```
    fileWriteNameStudy = 'ezConStudy' + fileNameLast.split(os.path.sep)[-1][:-4] + '.txt'
```
To :
```
    fileWriteNameStudy = fileNameLast.split(os.path.sep)[-1][:-4] + '_ezConStudy.txt'
```
