### ISSUE TITLE
ezCol.py crash during 37 plotting ezCon088antBTVTByFreqBinAllFall.png

### ISSUE THREAD

**Issue by StudioDanton** [tedcline/ezRA#6]
Hi Ted,

Had a crash trying to use for the first time ezCon.py to process a 2 hours acquisition test.
If necessary, I can provide the full output log or the input file.

### Setup

**Acquisition :**
Host: Intel D945GSEJT Intel Atom(TM) CPU N270 @ 1.60GHz
OS : Debian BunsenLab 6.1.85-1 (2024-04-11) i686 GNU/Linux
Kernel:  6.1.0-20-686-pae
SDR : Realtek RTL2838 DVB-T
Python v3.11.2
using programRevision = `ezCol231211a.py`

**Processing :**
OS: Windows 10 x64 22H2 Build 19045.4412
Python v3.8.10
using programRevision = `ezCon240108a.py`

### Commands

Failed when using commands:
`python ../ezRA/ezCon.py data/ObsStJean240524_19.txt`

### Input data

```
.\data/ObsStJean240524_19.txt
   dataAzimuth   =  180.0
   dataElevation =  42.0

 file = 0 of 1 in dir 1 of 1 = .\data/ObsStJean240524_19.txt samplesRead= 1   fileRawLen= 1   rawLen= 1   antLen ?= 1     
 [...]        
 file = 0 of 1 in dir 1 of 1 = .\data/ObsStJean240524_19.txt samplesRead= 83   fileRawLen= 83   rawLen= 83   antLen ?= 83             
                                                                                                                                                              
                         Total           samples read   = 83
                         Total reference samples read   = 0

   ezConAntXInput changed to 4 for AntB
```

### Output on Failure

```
  data/ObsStJean240524_19.txt  37 plotting ezCon088antBTVTByFreqBinAllFall.png ================================
Traceback (most recent call last):
  File "../ezRA/ezCon.py", line 10345, in <module>
    main()
  File "../ezRA/ezCon.py", line 10259, in main
    plotEzCon088antXTVTByFreqBinAllFall()
  File "../ezRA/ezCon.py", line 5976, in plotEzCon088antXTVTByFreqBinAllFall
    antXTVTD[:, n] = np.mean(antXTVT[:, downsamplingIndex:downsamplingIndex+downsamplingStep], axis=1)
IndexError: index 83 is out of bounds for axis 1 with size 83
```

**Comment by StudioDanton** [comment]
After analysing `ezCon.py`, I've found that every time I find `downsamplingStep` there is a variable :
`antXTVTDLen = 100 # quantity of spectra after downsampling` wich suggest a minimum of samples is needed in input.

To overcome the error and generate the other plots, I've add several time a small protection with the if bloc :

```
        # downsampling by averaging
        downsamplingStep = antLen // antXTVTDLen
        if downsamplingStep < 1:
            print('  Error downsamplingStep =', downsamplingStep)
            return(1)
```
